Remove windows from CI temporarily
For some reason, windows fails because "The filename or extension is too long"

```
C:\Rust\.cargo\bin\cargo.exe test
    Updating crates.io index
    Updating git repository `https://github.com/swc-project/swc`
error: failed to get `swc` as a dependency of package `toast v0.1.0 (D:\a\toast\toast\toast)`
Error: failed to get `swc` as a dependency of package `toast v0.1.0 (D:\a\toast\toast\toast)`
Caused by:
  failed to load source for dependency `swc`

Caused by:
  Unable to update https://github.com/swc-project/swc#61e58d73

Caused by:
  failed to stat 'C:/Users/runneradmin/.cargo/git/checkouts/swc-594f88c93b4170b2/61e58d7/ecmascript/parser/tests/typescript/tsc/internalModules/DeclarationMerging/ClassAndModuleThatMergeWithModulesExportedGenericFunctionAndNonGenericClassStaticFunctionOfTheSameName/input.ts.json': The filename or extension is too long.
  ; class=Os (2); code=Exists (-4)
```